          
name: notification-ms-ci-cd
on:
  workflow_dispatch:
    inputs:
      deploy_environment:
        description: Environment to deploy
        type: choice
        required: true
        default: dev
        options:
          - dev
          - test
          - prod

jobs:
  
  python-test-build-push:    
    name: python test build push
    uses: equality-tech/i27-helpdesk-devops/.github/workflows/wf-reuse-python.yaml@main 
    with:
      DOCKER_IMAGE_NAME: equalitytech/i27-notification-ms
      DOCKERHUB_USERNAME: ${{vars.DOCKERHUB_USERNAME}}
      environment: ${{ github.event.inputs.deploy_environment }}
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      